---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles # todo fix path
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - autoconf
  - bash
  - bash-completion
  - ctop
  - docker
  - docker-compose
  - docker-machine
  - docker-machine-driver-xhyve
  - git
  - go
  - homebrew/cask-fonts/font-menlo-for-powerline
  - htop
  - nmap
  - node
  - ssh-copy-id
  - readline
  - openssl
  - packer
  - pv
  - readline
  - ssh-copy-id
  - terraform
  - tig
  - tldr
  - watch
  - wget

homebrew_taps:
  - homebrew/cask
  - homebrew/core

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - alfred
  - appcode
  - battle-net
  - bettertouchtool
  - caskroom/cask
  - caskroom/versions/firefox-developer-edition
  - cleanmymac
  - dash
  - datagrip
  - firefox
  - gitify
  - google-chrome
  - intellij
  - iterm2
  - java
  - kaleidoscope
  - mysqlworkbench
  - phpstorm
  - postman
  - pycharm
  - reggy
  - sequel-pro
  - skype
  - slack
  - spotify
  - steam
  - sublime-text
  - telegram
  - transmit
  - tunnelblick
  - vagrant
  # - virtualbox
  # - virtualbox-extension-pack
  - visual-studio-code
  - vlc
  - whatsapp

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: [
  # - keynote
  # - kindle
  # - mindnode pro 1
  # - numbers
  # - onenote
  # - pixelmator
  # - pocket
  # - the unarchiver
  # - wunderlist
  # - xcode
]
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

# TODO: Add oh-my-zsh and its config (zshrc, powerline fonts)
